### ISSUE TITLE
pulsar-admin sinks localrun options

### ISSUE THREAD

**Issue by allnode-github** [streamnative/mop#145]
The program example in the sins pulse to PostgreSQL document is based on the cluster environment. The database table cannot be successfully inserted in the stand-alone mode. Can you create a new configuration example in the stand-alone mode? In stand-alone mode, pulsar 2.8.1.0, mop 2.8.1.0, pulsar-io-jdbc-postgres-2.8.0.nar
I want to run Pulsar to PostgresQL Sink and Pulsar to postgresQL Sink on a single machine without any exception. I also want to subscribe to the topic messages sent to Pulsar by the test client using MOP 2.8.1.0 and Pulsar 2.8.1.0. Pulsar-io-jdbc-postgres-2.8.0. nar, but messages cannot be written to the postgresQL database table pulsar-postgres-jdbc-sink. Later, I found that there was a Pulsar-Admin sinks localrun options. In the document, there was an example of collocation in the cluster environment, but collocation in the single-machine environment only explained without program examples. Could someone give me an example of running the PostgresQL Sink configuration file in single-machine mode?

**Comment by Technoboy-** [comment]
Hi， move this issue to [apache#pulsar](https://github.com/apache/pulsar)
