### ISSUE TITLE
mop turns on the permission function, and the proxy port 5682 does not have permission

### ISSUE THREAD

**Issue by beyondyinjl2** [streamnative/mop#207]
mop opens the permission function, uses mqtt1883 port to connect, sending and subscribing to topics without permission will prompt no permission and disconnect, but when using proxy 5682, sending and subscribing to topics without permission do not prompt without permission and disconnect

1 First use a topic with permission to send, and then use a topic without permission to send
2 First use the topic without permission, and send it after using the topic with permission

**Comment by Technoboy-** [comment]
Stale question, closed.
