### ISSUE TITLE
Verify mop works on Pulsar 2.6.1

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/mop#21]

**Comment by wolfstudy** [comment]
https://github.com/streamnative/mop/issues/20#issuecomment-709898836

**Comment by wolfstudy** [comment]
In the version of pulsar 2.6.1, mop does not work properly, this is because mop currently uses the version of pulsar 2.6.0, which leads to incompatibility

**Comment by codelipenghui** [comment]
@wolfstudy Could you please push a fix for it?

**Comment by wolfstudy** [comment]
> @wolfstudy Could you please push a fix for it?

Sure, https://github.com/streamnative/mop/pull/22 is fixing the issue.
