### ISSUE TITLE
[Discuss] About `mqttAuthenticationEnabled` and `mqttAuthorizationEnabled`

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#211]
## Motivation
if user set `mqttAuthenticationEnabled`, it also need to configure `authenticationEnabled`.
And if user set `mqttAuthorizationEnabled`, it also need to configure `authorizationEnabled`.

This could make mop users curious that why not only use `authenticationEnabled` or `authorizationEnabled`.

Benefit:
If pulsar set `authenticationEnabled=true`, but mop `mqttAuthenticationEnabled=false`, mop users doesn't need to authenticate. 
But if mop users need to authenticate/authorize, all the two params should be configured.

**Comment by mattisonchao** [comment]
Are the steps in this process correct?

authenticationEnabled=true && mqttAuthenticationEnabled=ture => user need authenticate.
authenticationEnabled=true && mqttAuthenticationEnabled=false => user do not need authenticate.
authenticationEnabled=false && mqttAuthenticationEnabled=true => user need authenticate.
authenticationEnabled=false && mqttAuthenticationEnabled=false => user do need authenticate.

**Comment by liangyuanpeng** [comment]
> Are the steps in this process correct?
> 
> authenticationEnabled=true && mqttAuthenticationEnabled=ture => user need authenticate. authenticationEnabled=true && mqttAuthenticationEnabled=false => user do not need authenticate. authenticationEnabled=false && mqttAuthenticationEnabled=true => user need authenticate. authenticationEnabled=false && mqttAuthenticationEnabled=false => user do need authenticate.

It's mean pulsar must be enable auth if mqtt server need to use auth. I agree it.  

> authenticationEnabled=false && mqttAuthenticationEnabled=true => user need authenticate. 
> authenticationEnabled=false && mqttAuthenticationEnabled=false => user do need authenticate.

MOP user don't need to authenticate.
