### ISSUE TITLE
Investigate Oauth2 and try to support it.

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#220]

**Comment by mattisonchao** [comment]
#707 Support use Oauth2 token authorization with a custom provider.
But almost MQTT Clients don't support Oauth2 workflow. We may use some tricks to support it.

I will submit another pull request to add tests and explain it.

**Comment by mattisonchao** [comment]
On the broker side, we already support it by `org.apache.pulsar.broker.authentication.AuthenticationProviderToken`, And PR #707 support use Oauth2 token do authorisations. 
But it seems that almost most MQTT clients don't support Oauth2 workflow to get token, but they support passing token to broker as authentication, refer to Hive MQ link: https://www.hivemq.com/blog/mqtt-security -fundamentals-oauth-2-0-mqtt/
