### ISSUE TITLE
Pahomqtt connects to port 5682, and occasionally disconnects and returns 104.103 error code

### ISSUE THREAD

**Issue by beyondyinjl2** [streamnative/mop#242]
Pahomqtt is connected to port 5682. Within 2 hours of connection, the heartbeat packet is 60 seconds, and occasionally the connection is disconnected and the error code 104.103 is returned. This will not happen on port 1883.

**Comment by Technoboy-** [comment]
This error code is not in MQTT spec. Please help to give more exception stacktrace.
