### ISSUE TITLE
migrate project to Gradle.

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/mop#266]
**Is your enhancement request related to a problem? Please describe.**

I think we could migrate this project to Gradle. following case show why we need to do that :

![jwt4j9pml0](https://user-images.githubusercontent.com/74767115/141999611-bdd78457-46af-4526-89e4-5916e95b1b68.png)

Gradle is 1.7 times faster in running tests, and 30 times faster when the cache is turned on!

**Comment by Technoboy-** [comment]
We may support features first.

**Comment by mattisonchao** [comment]
ok, i will focus on support mqtt 5.0 first.
