### ISSUE TITLE
Report test coverage

### ISSUE THREAD

**Issue by timmyyuan** [streamnative/mop#277]
**Is your enhancement request related to a problem? Please describe.**
We need test coverage to measure the quality of tests in MoP.

**Describe the solution you'd like**
We can integrate some github actions/apps into MoP to report the test coverage.

Some useful references:
https://github.com/marketplace?type=actions&query=coverage+
https://github.com/marketplace?query=coverage&type=apps
https://docs.github.com/en/actions/learn-github-actions
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

**Additional context**
We encourage adding badges to reflect the test coverage

**Comment by mattisonchao** [comment]
@timmyyuan  thanks for your suggestion, we will do that later.

**Comment by codelipenghui** [comment]
Sorry @mattisonchao we have already started working on this part.

**Comment by mattisonchao** [comment]
@codelipenghui  ok ~ , thank you for the notification.

**Comment by yaalsn** [comment]
@codelipenghui PTAL https://github.com/streamnative/mop/pull/282 , Copying Codecov badge link needs to have permission to view repository settings.

**Comment by mattisonchao** [comment]
closed.
The PR is : https://github.com/streamnative/mop/pull/397
