### ISSUE TITLE
Improve CI experience

### ISSUE THREAD

**Issue by yaalsn** [streamnative/mop#309]
**Is your enhancement request related to a problem? Please describe.**

`pr_test` pipeline has a `build` job, and the execution timeout is set to 30min. When we see the historical data, the `test after build` step takes too long and about 96% execution time of the `build` job. We need to reduce the failure rate of the pipeline.

**Describe the solution you'd like**

Reduce the unit test execution time. 

How about running the `setup` and `cleanup` functions only once in the whole test classes and cases instead of every test class?

**Describe alternatives you've considered**

Change timeout-minutes from 30min to 50min.

**Additional context**

Is there any better solution? We can discuss in this issue.

**Comment by mattisonchao** [comment]
Firstly, I agree with your idea. 

The premise is that we need to refactor the tests to ensure that they will not be affected by each other.

And I have some another idea for this issue.

1. Classify tests. ( e.g flaky-test, unit-test, integration-test...  ) we can rerun some failed test individually.
2. Remove some redundant multiple parameters tests.
3. Best to add Github bot to rerun flaky test,I think it's better for contributors.

**Comment by yaalsn** [comment]
> @yaalsn
> 
> Firstly, I agree with your idea.
> 
> The premise is that we need to refactor the tests to ensure that they will not be affected by each other.
> 
> And I have some another idea for this issue.
> 
> 1. Classify tests. ( e.g flaky-test, unit-test, integration-test...  ) we can rerun some failed test individually.
> 2. Remove some redundant multiple parameters tests.
> 3. Best to add Github bot to rerun flaky test,I think it's better for contributors.

Thanks for your idea and I think it's cool.  

And I have a question.

**Comment by mattisonchao** [comment]
> > @yaalsn
> > Firstly, I agree with your idea.
> > The premise is that we need to refactor the tests to ensure that they will not be affected by each other.
> > And I have some another idea for this issue.
> > 
> > 1. Classify tests. ( e.g flaky-test, unit-test, integration-test...  ) we can rerun some failed test individually.
> > 2. Remove some redundant multiple parameters tests.
> > 3. Best to add Github bot to rerun flaky test,I think it's better for contributors.
> 
> Thanks for your idea and I think it's cool.
> 
> And I have a question: why the test run with fail(except timeout)? Is the fail test affeted by another?
> 
> In order to speed up pr test, I tried to run the tests parallel in this [PR](https://github.com/streamnative/mop/actions/runs/1568882260), and I didn't find any fail tests when running the test independently.

I think there are several reasons.

- Asynchronous cause flaky test.
- Github Resource limit.

@Technoboy-  

Do you have any idea ?
