### ISSUE TITLE
Upgrade log4j2 version to 2.16.0

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#322]

**Comment by mattisonchao** [comment]
@Technoboy- 

Should we cherry-pick to all version ?

PR : https://github.com/streamnative/mop/pull/321

**Comment by Technoboy-** [comment]
> @Technoboy-
> 
> Should we cherry-pick to all version ?
> 
> PR : #321

Yes, it works.

**Comment by Technoboy-** [comment]
Need to cherry-pick to branch-2.7, branch-2.8. branch-2.9

**Comment by mattisonchao** [comment]
work done.

**Comment by mattisonchao** [comment]
@Technoboy- 

I think we need to close this issue.

**Comment by Technoboy-** [comment]
> @Technoboy-
> 
> I think we need to close this issue.

Yes， and many thanks for your help .
