### ISSUE TITLE
The test is stuck at ``Waiting for status to be reported``

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/mop#396]
**Describe the bug**

The test is stuck at ``Waiting for status to be reported``.

Relate information :  https://github.com/streamnative/mop/pull/379#issuecomment-1009535644

**To Reproduce**

See PR #379 

**Expected behavior**

The test didn't get stuck.

**Screenshots**

![image](https://user-images.githubusercontent.com/74767115/148869715-8baae374-8c54-4048-bed6-278b9aabd507.png)

**Comment by mattisonchao** [comment]
@yaalsn 

Thanks a lot for your contribution.

**Comment by mattisonchao** [comment]
@Technoboy-  @codelipenghui 
https://github.community/t/expected-waiting-for-status-to-be-reported/18001

This article might help with that. But I have no right to try it.

**Comment by mattisonchao** [comment]
@Technoboy- 

https://github.community/t/expected-waiting-for-status-to-be-reported/18001

This article might help with that. But I have no right to try it.

**Comment by Technoboy-** [comment]
> @Technoboy-
> 
> https://github.community/t/expected-waiting-for-status-to-be-reported/18001
> 
> This article might help with that. But I have no right to try it.

Yes, try to remove it and then close-reopen pull request, then we find it works again...
