### ISSUE TITLE
[MIP-4] Introduce system topic to support client id unique

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#409]
## Motivation
The MQTT spec calls for terminating existing clients with the same ClientID on CONNECT. But currently, MoP is only implemented on the proxy or broker side, not across clusters.

## Goal
Introduce system topic and internal reader to support this.

## Implementation

We define a system topic called `__change_events`, when MoP starts, the internal reader will try to read this topic.
Any client connects to the broker, it will send a new event(contain client id) to the system topic, and other readers try to read and check if it contains the client id. When contains, it will try to close the connection.

This can keep the cluster that only one client id is online but due to the implementation, close the same client id in another MoP instance may delay.

**Comment by mattisonchao** [comment]
> when MoP starts, the internal reader will try to read this topic.
Any client connects to the broker, it will send a new event(contain client id) to the system topic, and other readers try to read and check if it contains the client id. When contains, it will try to close the connection.

If this feature is unique at namespace level, maybe we need to wait for this PR. https://github.com/apache/pulsar/pull/13813
