### ISSUE TITLE
Authentication and Authorisation for MQTT clients

### ISSUE THREAD

**Issue by josephglanville** [streamnative/mop#49]
Currently doesn't appear that MoP supports authentication or authorisation.

Ideally should support authentication and authorisation through existing extensible Pulsar interfaces.

**Comment by josephglanville** [comment]
So MQTT v3 doesn't supported the extended authentication required for challenge response mechanisms like SASL so that will have to wait for MQTT v5 support to be implemented.

For now I am going to take a swing at basic and token auth over TLS purely using the username/password fields in the connect packet.

**Comment by josephglanville** [comment]
For basic and token auth methods will need #51 implemented also.

**Comment by vicaya** [comment]
TLS support should be optional, IMO, as many load balancers (e.g. AWS NLB) support TLS termination, which is often preferred in many deployments. Let's get #55 merged.
