### ISSUE TITLE
single or multi level wildcard can we support?

### ISSUE THREAD

**Issue by hb-chen** [streamnative/mop#59]

**Comment by codelipenghui** [comment]
@hb-chen Do you mean the topic name? Currently, the topic name follows the Pulsar topic name pattern `tenant/namespace/topic`. Could you please more details about the requirement?

**Comment by hb-chen** [comment]
Topic name. Multi or single level wildcard `#` `+`.
For example `/a/b/#`、`/a/b/+`、`/a/+/c`、`/+/b/#` .

**Comment by codering** [comment]
I need it，too.

**Comment by codelipenghui** [comment]
@hb-chen I have pushed out the PR #95 supporting the single/multi wildcard
