### ISSUE TITLE
MQTT-SN support

### ISSUE THREAD

**Issue by julienlau** [streamnative/mop#62]
Hi,
Thanks for your work.

Does mop support MQTT-SN protocol (MQTT For Sensor Networks) over UDP ?

In addition, it would be nice to specify in the README which MQTT version is supported:  3.1.1 ? 5.0 ?

Regards

**Comment by codelipenghui** [comment]
Currently, does not support MQTT-SN protocol and the supported MQTT version is 3.1.1, we have updated the documentation and will close the issue first.

**Comment by julienlau** [comment]
Ok thanks
