### ISSUE TITLE
Request is denied: namespace=public/default

### ISSUE THREAD

**Issue by xiaoxiongmao-liu** [streamnative/mop#68]
Env:
   pulsar official helm deployed in k8s
version:
  pulsar:2.7.2
  mop:master
Exception:
  
![image](https://user-images.githubusercontent.com/24889764/126865490-4bdc1975-d8d9-4565-94e0-65cb06529b6c.png)

I try restart client to subscribe topic , and three or four times, one success，pls

**Comment by xiaoxiongmao-liu** [comment]
> Env:
> pulsar official helm deployed in k8s
> version:
> pulsar:2.7.2
> mop:master
> Exception:
> 
> ![image](https://user-images.githubusercontent.com/24889764/126865490-4bdc1975-d8d9-4565-94e0-65cb06529b6c.png)
> 
> I try restart client to subscribe topic , and three or four times, one success，pls

**Comment by xiaoxiongmao-liu** [comment]
I suppose that the exception is caused by https://github.com/apache/pulsar/issues/7517，but pulsar official do not support 2.8.0 helm

**Comment by xiaoxiongmao-liu** [comment]
My fault，I did not use proxy.Now, no problem.

**Comment by HankHannah** [comment]
@xiaoxiongmao-liu hi, could you pls tell me how to use proxy in k8s cluster? thanks in advanced
