### ISSUE TITLE
TLS PSK Support

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/mop#85]
Creating a venue in SmartZone results in a new configuration being added to SmartZone’s own mosquitto broker. The venue configuration at Figure 3 will result in the following lines:

```
address 201.52.221.208:8883
topic 3.0/LOC/lbstest/LS/# in
topic 3.0/LOC/lbstest/+/MGR out
bridge_tls_version tlsv1
bridge_identity lbstest
bridge_psk 7275636B757331323321
```

The first line is the IP address of the external location server. The topic lines allow the SZ mosquitto broker to receive results for multiple topics, and to send results ending with MGR to multiple location servers. The SZ mosquitto broker is running TLS version 1.0.

bridge_identity is the user name the SZ mosquitto broker will use to connect to the LS broker, and bridge_pskis the pre-shared key to authenticate the user. It is the hex conversion of the password that was entered when creating the venue. You can use the site https://www.rapidtables.com/convert/number/ascii-to-hex.html for the conversion. In the example above we used ruckus123! as the password/pre-shared key.

**Comment by Technoboy-** [comment]
From the document, maybe we don't need to do this.

**Comment by Technoboy-** [comment]
Some of the good references:
- https://bugs.openjdk.java.net/browse/JDK-8202625
- https://www.oracle.com/java/technologies/javase/11-relnote-issues.html
- https://docs.oracle.com/javame/8.3/api/ssl-extension/api/com/oracle/ssl/package-summary.html

And another third party provider (JCA_JCE):
- https://docs.oracle.com/cd/E80667_01/English/Installing/p6_eppm_install_config/helpmain.htm?toc.htm?89631.htm
- https://docs.oracle.com/cd/E80667_01/English/Installing/p6_eppm_install_config/helpmain.htm?toc.htm?89629.htm
- https://jce.iaik.tugraz.at/product-category/evaluationversions+isasilk/

**Comment by Technoboy-** [comment]
Add proxy tls-psk support by #147
