### ISSUE TITLE
[DISCUSSION] export metrics of mqtt

### ISSUE THREAD

**Issue by liangyuanpeng** [streamnative/mop#96]
I want to some metrics of mqtt, like `online_client_count`, `disconnected_client_count` in 5 min,  and seems like we can't get this metrics from pulsar api of `{PULSAR_IP}:{PORT}/metrics`.

Any idea for this? Alone start http for metrics?  I even hope that the metrics of pulsar have only one entrance -> `{PULSAR_IP}:{PORT}/metrics`

**Comment by codelipenghui** [comment]
@liangyepianzhou Pulsar supports metrics provider https://github.com/apache/pulsar/pull/9021 which can be used to expose the MoP metrics through the Pulsar metrics endpoint. Are you interested in the feature implement for MoP metrics?
